export const useWhiteboardStore = () => ({
  elements: [] as any[],
  selectedId: null as string | null,
  mode: 'select' as const,
  viewport: { translateX: 0, translateY: 0, scale: 1 },
  setMode: (_: any) => {},
  setViewport: (_: any) => {},
  clearAll: () => {},
  deleteSelected: () => {},
  select: (_: any) => {},
  addStroke: () => '',
  appendPointToStroke: () => {},
  addText: () => '',
  updateText: () => {},
  addEmoji: () => '',
  addIcon: () => '',
  moveElement: () => {},
  duplicateSelected: () => {},
  bringToFront: () => {},
  hitTest: () => null,
})
