export enum NavigationScreenName {
  LoginScreen = 'LoginScreen',
  Dashboard = 'Dashboard',
  Register = 'Register',
  Recovery = 'Recovery',
  Topic = 'Topic',
  CalendarScreen = 'CalendarScreen',
  CalendarAddScreen = 'CalendarAddScreen',
  CalendarDetailsScreen = 'CalendarDetailsScreen',
  ChallengeScreen = 'ChallengeScreen',
  ChallengeAddScreen = 'ChallengeAddScreen',
  ChallengeAddHangmanScreen = 'ChallengeAddHangmanScreen',
  ChallengeAddMatrixScreen = 'ChallengeAddMatrixScreen',
  ChallengeAddQuizScreen = 'ChallengeAddQuizScreen',
  ChallengeAddTextAnswerScreen = 'ChallengeAddTextAnswerScreen',
  TopicDetailsScreen = 'TopicDetailsScreen',
  SummaryScreen = 'SummaryScreen',
  SummaryAudioScreen = 'SummaryAudioScreen',
  ProfileScreen = 'ProfileScreen',
  ConnectionsScreen = 'ConnectionsScreen',
  PaymentScreen = 'PaymentScreen',
  NotificationsScreen = 'NotificationsScreen',
  SummaryListTab = 'SummaryListTab',
}
