#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🛡️  Pre-push: running lint and format checks"
npm run lint
npm run format:check

#TODO: # Uncomment the line below to run tests before pushing
# npm test -- --coverage

