#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🧹 Rodando lint-staged..."
yarn lint-staged

if [ $? -ne 0 ]; then
  echo "❌ Commit bloqueado: erros de lint encontrados."
  exit 1
fi

echo "✅ Lint OK! Prosseguindo com o commit..."
